package com.belledonne.ecommerce.enums;

public enum SecurityAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    OTP_VERIFIED,
    OTP_FAILED,
    TOKEN_REFRESH,
    LOGOUT,
    ADMIN_UNLOCK_ACCOUNT,
    ADMIN_BLOCK_USER,
    ADMIN_UNBLOCK_USER,
    ADMIN_DELETE_USER,
    ADMIN_LOGIN,
    ADMIN_ACTION,
    ADMIN_EXPORT_LOGS,
    SECURITY_ALERT_TRIGGERED,
    SUSPICIOUS_ACTIVITY
}
